name: deploy m3ntorshipcom to playground cluster

on:
  push:
    branches:
      # - develop
      # - playground-deployment
      - playground-deployment-fullstack
env:
  # fixed deployment envs
  M3_IMAGE_FRONTEND: ${{ secrets.M3_DOCKER_HOST }}/m3ntorshipcom-frontend
  M3_IMAGE_BACKEND: ${{ secrets.M3_DOCKER_HOST }}/m3ntorshipcom-backend
  M3_IMAGE_STORYBOOK: ${{ secrets.M3_DOCKER_HOST }}/m3ntorshipcom-storybook
  M3_DOCKER_FILE_FRONTEND: Dockerfile.playground.frontend
  M3_DOCKER_FILE_BACKEND: Dockerfile.playground.backend
  M3_DOCKER_FILE_STORYBOOK: Dockerfile.playground.storybook

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - run: echo 'deploy cms to playground cluster'