name: deploy storybook to playground cluster

on:
  push:
    branches:
      - playground-deployment-storybook
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v1
      # dynamic deployment envs
      - name: set templating envs
        id: version
        run: |
          echo ::set-output name=version::$(git rev-parse --short=4 ${{ github.sha }})
  test-env:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.prepare.outputs.version }}
